### ISSUE TITLE
Change Food types and cocktails label to say 'What to expect'

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#97]

**Comment by lolmos** [comment]
done

**Comment by angievanhegan** [comment]
@lolmos I can still see 'cocktails' here: 

https://the.holboxeno.com/food-drink-in-holbox/bar-arena
https://the.holboxeno.com/food-drink-in-holbox/cariocas-beach-bar
https://the.holboxeno.com/food-drink-in-holbox/ambar

Should it be here, even if there's no text in there?
